### ISSUE TITLE
Popup content gets lost on the client side (Second try)

### ISSUE THREAD

**Issue by robaca** [wolfie/PopupExtension#9]
Hi, 

as the bugfix for issue #8 did not solve our specific problem, but seems to fix some other, I created a new ticket and also created an example application that hopefully helps understanding how we try to use the PopupExtension.

The example project can by found at https://github.com/cmjartan/PopupExtensionExample

We would expect that an opened popup stays open if switch to another view and then back. 
It should also be possible that every view has it's own independent popup opened without interfering.

**Comment by wolfie** [comment]
Thanks for the example! I'll probably take a look at this before next week.

**Comment by wolfie** [comment]
Changing views with Navigator seems to lose track of the previous view's PopupExtensionDataTransferComponent. Toggling the views back and forth before even opening the popups seems to lose track of both PopupExtensionDataTransferComponents.

This might be a failure due to too much combined magic regarding Navigator and PopupExtension's `extend()` method (since it tries to automagically ninja-hide the data transfer component .. _somewhere_), which happens to work sometimes, but in non-trivial cases it doesn't.

I was able to fix the example application you provided by changing the `PopupExtension.extend` invocation to `PopupExtension.extendWithManualBundle` and adding the provided data transfer component into the View itself. This retained the popup contents in my testing.

While this kind-of-sort-of is a genuine issue, I'm going to close this as "wontfix", because I'm a lazy bastard and on the last day of my vacation :). Maybe I'll do a more sane implementation if and when Vaadin supports sending components over the wire explicitly through states or RPC. In the future, I probably should deprecate the magic `extend` method, and either redirect users to the `extendWithManualBundle`, or replace it altogether.
